### ISSUE TITLE
ENUM not support through Filter

### ISSUE THREAD

**Issue by jigargadhiya-ss** [smartSenseSolutions/smartsense-java-commons#1]
**Issue** :  If we want to apply filter on any ENUM field then it gives an error of casting. 
```
FilterRequest mustWhere = request.getFilterRequest();
mustWhere.appendCriteria(TableFieldConstants.STATUS, Operator.IN, status);
```

If above STATUS field is ENUM then it will throw can not cast exception. 

**Solutions**:
ENUM specification should be prepare like below. 

`Specification<PairRequests> spec = (root, query, qb) -> qb.equal(root.get("status").as(String.class), "value");`

Above specification cast filed into text and queries as string. So all operation from String can be done on ENUM  e.g like, equals, notEquals etc. For IN specification can be prepared like below. 

`Specification<PairRequests> spec = (root, query, qb) -> root.get("status").as(String.class).in(valueList);`

**Comment by sunil-smartsense** [comment]
Merging it with #4

**Comment by sunil-kanzar-01** [comment]
Merge with #4
