### ISSUE TITLE
Unnecessary criteria needs to pass when custom specification given in filter method argument. 

### ISSUE THREAD

**Issue by jigargadhiya-ss** [smartSenseSolutions/smartsense-java-commons#2]
https://github.com/smartSenseSolutions/smartsense-java-commons/blob/5ec25ee45fa8c3d5e7f7f49991316738238d0165/commons-dao/src/main/java/com/smartsensesolutions/java/commons/base/service/BaseService.java#L148C16-L148C16

Issue :  If custom specification is passed and no criteria are set in FilterRequest object then specification will be ignored in findAll method. 

WorkAround: Set any dummy criteria in FilterRequest and pass required specification.

**Comment by sunil-kanzar-01** [comment]
Merge with #4
